global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: null
rule_files: null
scrape_configs:
  - job_name: kafka
    static_configs:
      - targets:
          - jmx-kafka101:5556
          - jmx-kafka102:5556
<<<<<<< HEAD
          - jmx-kafka103:5556
=======
          - jmx-kafka103:5556
>>>>>>> f3c1ad006c2a2b461708a81564853b870761426f
