version: '3'
services:
  grafana:
    image: 'grafana/grafana'
    ports:
      - '3000:3000'
    environment:
      GF_PATHS_DATA: /var/lib/grafana
      GF_SECURITY_ALLOW_EMBEDDING: 'true'
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_SMTP_ENABLED: true
      GF_SECURITY_ADMIN_PASSWORD: kaffia
    volumes:
      - ../grafana/provisioning:/etc/grafana/provisioning
      - ../grafana/dashboards:/var/lib/grafana/dashboards
    container_name: grafana
    depends_on:
      - prometheus
  prometheus:
    image: 'prom/prometheus'
    ports:
      - '9090:9090'
    volumes:
      - ../prometheus/prometheus.yml:/../prometheus/prometheus.yml
    command: '--config.file=/../prometheus/prometheus.yml'
    container_name: prometheus
  zk1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - 2181:2181
    container_name: zookeeper1
